general {
    lock_cmd = systemctl --user start frost-lock.service
    before_sleep_cmd = systemctl --user start frost-lock.service
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
    timeout = 900
    on-timeout = systemctl --user start frost-lock.service
}

listener {
    timeout = 960
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}
