general {
    hide_cursor = true
    ignore_empty_input = false
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }

    fingerprint {
        enabled = false
    }
}

background {
    monitor =
    color = rgba(08111cff)
}

label {
    monitor =
    text = $TIME
    color = rgba(e8f1ffff)
    font_size = 72
    position = 0, 90
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.28
    outer_color = rgba(9ed8ffff)
    inner_color = rgba(101a28e6)
    font_color = rgba(e8f1ffff)
    fade_on_empty = false
    placeholder_text = <span foreground="##a8bbd2">Senha</span>
    fail_text = <span foreground="##ff8f9b">Falha ($ATTEMPTS)</span>
    position = 0, -100
    halign = center
    valign = center
}
