schemaVersion = 1
name = "Osaka Jade"
mode = "dark"
icon = "Yaru-prussiangreen"

[colors]
background = "#111c18"
foreground = "#c1c497"
muted = "#53685b"
accent = "#509475"
urgent = "#ff5345"
highlight = "#459451"
success = "#549e6a"
warning = "#a2734b"
selection = "#32473b"
dark_background = "#0c1512"
darker_background = "#090f0d"
lighter_background = "#23372b"
dark_foreground = "#81b8a8"
light_foreground = "#d6d5bc"
bright_foreground = "#f7e8b2"
red = "#ff5345"
yellow = "#459451"
orange = "#a2734b"
green = "#549e6a"
cyan = "#2dd5b7"
blue = "#509475"
magenta = "#d2689c"
brown = "#513925"
bright_red = "#db9f9c"
bright_yellow = "#e5c736"
bright_green = "#63b07a"
bright_blue = "#acd4cf"
