schemaVersion = 1
name = "Flexoki Light"
mode = "light"
icon = "Yaru-blue"

[colors]
background = "#fffcf0"
foreground = "#100f0f"
muted = "#b7b5ac"
accent = "#205ea6"
urgent = "#d14d41"
highlight = "#d0a215"
success = "#879a39"
warning = "#d0772b"
selection = "#cecdc3"
dark_background = "#f2efe4"
darker_background = "#e5e2d8"
lighter_background = "#e6e4d9"
dark_foreground = "#878580"
light_foreground = "#403e3c"
bright_foreground = "#100f0f"
red = "#d14d41"
yellow = "#d0a215"
orange = "#d0772b"
green = "#879a39"
cyan = "#3aa99f"
blue = "#205ea6"
magenta = "#ce5d97"
brown = "#683b15"
bright_red = "#d14d41"
bright_yellow = "#d0a215"
bright_green = "#879a39"
bright_blue = "#4385be"
