schemaVersion = 1
name = "Catppuccin Latte"
mode = "light"
icon = "Yaru-blue"

[colors]
background = "#eff1f5"
foreground = "#4c4f69"
muted = "#acb0be"
accent = "#1e66f5"
urgent = "#d20f39"
highlight = "#df8e1d"
success = "#40a02b"
warning = "#d84e2b"
selection = "#ccd0da"
dark_background = "#e3e4e8"
darker_background = "#d7d8dc"
lighter_background = "#dce0e8"
dark_foreground = "#9ca0b0"
light_foreground = "#5c5f77"
bright_foreground = "#4c4f69"
red = "#d20f39"
yellow = "#df8e1d"
orange = "#d84e2b"
green = "#40a02b"
cyan = "#179299"
blue = "#1e66f5"
magenta = "#ea76cb"
brown = "#6c2715"
bright_red = "#d20f39"
bright_yellow = "#df8e1d"
bright_green = "#40a02b"
bright_blue = "#1e66f5"
