background = {{background_strip}}
foreground = {{foreground_strip}}
selection-background = {{selection_strip}}
selection-foreground = {{foreground_strip}}
cursor-color = {{foreground_strip}}
palette = 0={{dark_background}}
palette = 1={{red}}
palette = 2={{green}}
palette = 3={{yellow}}
palette = 4={{blue}}
palette = 5={{magenta}}
palette = 6={{cyan}}
palette = 7={{foreground}}
palette = 8={{muted}}
palette = 9={{bright_red}}
palette = 10={{bright_green}}
palette = 11={{bright_yellow}}
palette = 12={{bright_blue}}
palette = 13={{magenta}}
palette = 14={{cyan}}
palette = 15={{bright_foreground}}
