schemaVersion = 1
name = "Miasma"
mode = "dark"
icon = "Yaru-olive"

[colors]
background = "#222222"
foreground = "#c2c2b0"
muted = "#666666"
accent = "#78824b"
urgent = "#685742"
highlight = "#b36d43"
success = "#5f875f"
warning = "#8d6242"
selection = "#383838"
dark_background = "#191919"
darker_background = "#121212"
lighter_background = "#2c2c2c"
dark_foreground = "#555555"
light_foreground = "#8a8a7e"
bright_foreground = "#c2c2b0"
red = "#685742"
yellow = "#b36d43"
orange = "#8d6242"
green = "#5f875f"
cyan = "#c9a554"
blue = "#78824b"
magenta = "#bb7744"
brown = "#463121"
bright_red = "#685742"
bright_yellow = "#b36d43"
bright_green = "#5f875f"
bright_blue = "#78824b"
