schemaVersion = 1
name = "Last Horizon"
mode = "dark"
icon = "Yaru-wartybrown"

[colors]
background = "#0c0b0c"
foreground = "#fafcfb"
muted = "#584e51"
accent = "#b59790"
urgent = "#c38b7b"
highlight = "#6b5e73"
success = "#87a9b0"
warning = "#6b5e73"
selection = "#584e51"
dark_background = "#090809"
darker_background = "#060606"
lighter_background = "#0c0b0c"
dark_foreground = "#584e51"
light_foreground = "#cfd3cd"
bright_foreground = "#e2dddc"
red = "#c38b7b"
yellow = "#6b5e73"
green = "#87a9b0"
cyan = "#a5a0b6"
blue = "#b59790"
magenta = "#c4d8e2"
bright_red = "#c38b7b"
bright_yellow = "#6b5e73"
bright_green = "#87a9b0"
bright_blue = "#b59790"
