schemaVersion = 1
name = "Hackerman"
mode = "dark"
icon = "Yaru-sage"

[colors]
background = "#0b0c16"
foreground = "#ddf7ff"
muted = "#2d3450"
accent = "#82fb9c"
urgent = "#50f872"
highlight = "#50f7d4"
success = "#4fe88f"
warning = "#50f7a3"
selection = "#1f253a"
dark_background = "#080910"
darker_background = "#06060c"
lighter_background = "#151828"
dark_foreground = "#6a6e95"
light_foreground = "#b5c5db"
bright_foreground = "#ddf7ff"
red = "#50f872"
yellow = "#50f7d4"
orange = "#50f7a3"
green = "#4fe88f"
cyan = "#7cf8f7"
blue = "#829dd4"
magenta = "#86a7df"
brown = "#287b51"
bright_red = "#85ff9d"
bright_yellow = "#a4ffec"
bright_green = "#9cf7c2"
bright_blue = "#c4d2ed"
