schemaVersion = 1
name = "Everforest"
mode = "dark"

[colors]
background = "#2d353b"
foreground = "#d3c6aa"
muted = "#475258"
accent = "#7fbbb3"
urgent = "#e67e80"
highlight = "#dbbc7f"
success = "#a7c080"
warning = "#e09d7f"
selection = "#3d484d"
dark_background = "#21272c"
darker_background = "#181d20"
lighter_background = "#343f44"
dark_foreground = "#4f585e"
light_foreground = "#9da9a0"
bright_foreground = "#d3c6aa"
red = "#e67e80"
yellow = "#dbbc7f"
orange = "#e09d7f"
green = "#a7c080"
cyan = "#83c092"
blue = "#7fbbb3"
magenta = "#d699b6"
brown = "#704e3f"
bright_red = "#e67e80"
bright_yellow = "#dbbc7f"
bright_green = "#a7c080"
bright_blue = "#7fbbb3"
