schemaVersion = 1
name = "Ethereal"
mode = "dark"

[colors]
background = "#060b1e"
foreground = "#ffcead"
muted = "#6d7db6"
accent = "#7d82d9"
urgent = "#ed5b5a"
highlight = "#e9bb4f"
success = "#92a593"
warning = "#eb8b54"
selection = "#252e56"
dark_background = "#040816"
darker_background = "#030610"
lighter_background = "#131a3a"
dark_foreground = "#6d7db6"
light_foreground = "#c9b8a6"
bright_foreground = "#ffcead"
red = "#ed5b5a"
yellow = "#e9bb4f"
orange = "#eb8b54"
green = "#92a593"
cyan = "#a3bfd1"
blue = "#7d82d9"
magenta = "#c89dc1"
brown = "#75452a"
bright_red = "#faaaa9"
bright_yellow = "#f7dc9c"
bright_green = "#c4cfc4"
bright_blue = "#c2c4f0"
